# Generated by Django 4.0.3 on 2022-06-09 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='myOrder',
            new_name='order',
        ),
    ]
